[workspace]
members = [
    "apps",
    "domain/model",
    "domain/usecase",
    "gateway/dummy_gateway",
    "gateway/http_handlers",
    "libs",
    "macros",
]
resolver = "2"

[workspace.dependencies]
# Internal crates
domain-model = { path = "domain/model" }
domain-usecase = { path = "domain/usecase" }
dummy_gateway = { path = "gateway/dummy_gateway" }
http_handlers = { path = "gateway/http_handlers" }
libs = { path = "libs" }

# External dependencies
actix-cors = "0.7"
actix-web = "4"
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
